### ISSUE TITLE
This repo exposes paid plugin to public!

### ISSUE THREAD

**Issue by KirillKuzyk** [noxden/DeckOne#13]
Hi,

This is Kirill, creator of the plugin:
https://assetstore.unity.com/packages/tools/utilities/ar-foundation-editor-remote-168773

Please make your repository private because it exposes the plugin's source code to the public. To be exact, the 'Plugins/ARFoundationRemoteInstaller/' folder.

An alternative to making your repo private is to remove the plugin from your git repo AND clean the commit history:
https://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github

Thanks for your understanding.

**Comment by noxden** [comment]
Thank you for pointing that out!
I think I fixed it now. And again, sorry about this.
